// CSGO Cases and Items Data

const rarityWeights = {
    'Consumer Grade': 0.7992,
    'Industrial Grade': 0.1598,
    'Mil-Spec': 0.032,
    'Restricted': 0.0064,
    'Classified': 0.00128,
    'Covert': 0.00026,
    'Rare Special': 0.00026
};

const cases = [
    {
        id: 'weapon-case-1',
        name: 'CS:GO Weapon Case',
        price: 2.49,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZmY2YjAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZmY4YzAwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2cxKSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSIxMDAiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNiIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPldlYXBvbjwvdGV4dD48dGV4dCB4PSIxMDAiIHk9IjEyMCIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmaWxsPSIjZmZmIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5DYXNlPC90ZXh0PjxjaXJjbGUgY3g9IjEwMCIgY3k9IjE0MCIgcj0iNiIgZmlsbD0iI2ZmZDcwMCIvPjwvc3ZnPg==',
        items: [
            { name: 'MP9 | Hot Rod', rarity: 'Covert', price: 150.00 },
            { name: 'AK-47 | Case Hardened', rarity: 'Classified', price: 85.00 },
            { name: 'Desert Eagle | Hypnotic', rarity: 'Classified', price: 42.00 },
            { name: 'AWP | Lightning Strike', rarity: 'Covert', price: 320.00 },
            { name: 'M4A1-S | Dark Water', rarity: 'Restricted', price: 15.00 },
            { name: 'Glock-18 | Dragon Tattoo', rarity: 'Restricted', price: 12.00 },
            { name: 'USP-S | Dark Water', rarity: 'Restricted', price: 8.00 },
            { name: 'SG 553 | Ultraviolet', rarity: 'Mil-Spec', price: 3.50 },
            { name: 'M4A4 | Faded Zebra', rarity: 'Mil-Spec', price: 2.80 },
            { name: 'AUG | Wings', rarity: 'Mil-Spec', price: 2.20 },
            { name: 'P90 | Teardown', rarity: 'Industrial Grade', price: 1.20 },
            { name: 'Nova | Candy Apple', rarity: 'Industrial Grade', price: 0.80 },
            { name: 'Tec-9 | Groundwater', rarity: 'Industrial Grade', price: 0.50 },
            { name: 'MP7 | Skulls', rarity: 'Consumer Grade', price: 0.20 },
            { name: 'P250 | Boreal Forest', rarity: 'Consumer Grade', price: 0.15 },
            { name: '★ Karambit', rarity: 'Rare Special', price: 800.00 }
        ]
    },
    {
        id: 'chroma-case',
        name: 'Chroma Case',
        price: 2.99,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcyIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojNGI2OWZmIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojODg0N2ZmIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2cyKSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSIxMDUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxOCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkNocm9tYTwvdGV4dD48Y2lyY2xlIGN4PSI4MCIgY3k9IjE0MCIgcj0iNSIgZmlsbD0iI2ZmMDAwMCIvPjxjaXJjbGUgY3g9IjEwMCIgY3k9IjE0MCIgcj0iNSIgZmlsbD0iIzAwZmYwMCIvPjxjaXJjbGUgY3g9IjEyMCIgY3k9IjE0MCIgcj0iNSIgZmlsbD0iIzAwMDBmZiIvPjwvc3ZnPg==',
        items: [
            { name: 'AK-47 | Fire Serpent', rarity: 'Covert', price: 450.00 },
            { name: 'M4A4 | Howl', rarity: 'Covert', price: 2500.00 },
            { name: 'Galil AR | Chatterbox', rarity: 'Classified', price: 35.00 },
            { name: 'M4A1-S | Cyrex', rarity: 'Classified', price: 65.00 },
            { name: 'Desert Eagle | Naga', rarity: 'Restricted', price: 18.00 },
            { name: 'Dual Berettas | Urban Shock', rarity: 'Restricted', price: 8.00 },
            { name: 'MAC-10 | Graven', rarity: 'Restricted', price: 5.00 },
            { name: 'SCAR-20 | Cyrex', rarity: 'Mil-Spec', price: 3.20 },
            { name: 'MP9 | Dart', rarity: 'Mil-Spec', price: 2.50 },
            { name: 'Sawed-Off | Serenity', rarity: 'Mil-Spec', price: 2.00 },
            { name: 'P250 | Muertos', rarity: 'Industrial Grade', price: 1.50 },
            { name: 'XM1014 | Quicksilver', rarity: 'Industrial Grade', price: 0.90 },
            { name: 'Negev | Man-o\'-war', rarity: 'Industrial Grade', price: 0.70 },
            { name: 'P2000 | Grassland', rarity: 'Consumer Grade', price: 0.25 },
            { name: 'Five-SeveN | Nitro', rarity: 'Consumer Grade', price: 0.18 },
            { name: '★ Butterfly Knife', rarity: 'Rare Special', price: 1200.00 }
        ]
    },
    {
        id: 'chroma-2-case',
        name: 'Chroma 2 Case',
        price: 2.75,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImczIiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZDMyY2U2Ii8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZWI0YjRiIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2czKSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSI5NSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2hyb21hIDI8L3RleHQ+PHRleHQgeD0iMTAwIiB5PSIxMTUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxMiIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2FzZTwvdGV4dD48cmVjdCB4PSI3MCIgeT0iMTI1IiB3aWR0aD0iNjAiIGhlaWdodD0iMjAiIGZpbGw9IiNmZmQ3MDAiIHJ4PSI1Ii8+PC9zdmc+',
        items: [
            { name: 'M4A1-S | Hyper Beast', rarity: 'Covert', price: 95.00 },
            { name: 'Galil AR | Eco', rarity: 'Classified', price: 28.00 },
            { name: 'Five-SeveN | Monkey Business', rarity: 'Classified', price: 38.00 },
            { name: 'AWP | Man-o\'-war', rarity: 'Classified', price: 45.00 },
            { name: 'CZ75-Auto | Pole Position', rarity: 'Restricted', price: 12.00 },
            { name: 'Desert Eagle | Naga', rarity: 'Restricted', price: 16.00 },
            { name: 'MAC-10 | Neon Rider', rarity: 'Restricted', price: 10.00 },
            { name: 'SCAR-20 | Grotto', rarity: 'Mil-Spec', price: 3.80 },
            { name: 'MP7 | Armor Core', rarity: 'Mil-Spec', price: 2.90 },
            { name: 'Negev | Man-o\'-war', rarity: 'Mil-Spec', price: 2.30 },
            { name: 'UMP-45 | Grand Prix', rarity: 'Industrial Grade', price: 1.40 },
            { name: 'P250 | Valence', rarity: 'Industrial Grade', price: 0.95 },
            { name: 'Sawed-Off | Origami', rarity: 'Industrial Grade', price: 0.65 },
            { name: 'Dual Berettas | Moon in Libra', rarity: 'Consumer Grade', price: 0.30 },
            { name: 'AK-47 | Elite Build', rarity: 'Consumer Grade', price: 0.22 },
            { name: '★ Huntsman Knife', rarity: 'Rare Special', price: 950.00 }
        ]
    },
    {
        id: 'chroma-3-case',
        name: 'Chroma 3 Case',
        price: 2.50,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc0IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojNWU5OGQ5Ii8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojNGI2OWZmIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2c0KSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSI5NSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2hyb21hIDM8L3RleHQ+PHRleHQgeD0iMTAwIiB5PSIxMTUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxMiIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2FzZTwvdGV4dD48cG9seWdvbiBwb2ludHM9IjEwMCwxMjUgMTEwLDE0NSA5MCwxNDUiIGZpbGw9IiNmZmQ3MDAiLz48L3N2Zz4=',
        items: [
            { name: 'PP-Bizon | Judgement of Anubis', rarity: 'Covert', price: 75.00 },
            { name: 'M4A1-S | Chantico\'s Fire', rarity: 'Classified', price: 55.00 },
            { name: 'Tec-9 | Re-Entry', rarity: 'Classified', price: 32.00 },
            { name: 'G3SG1 | Stinger', rarity: 'Restricted', price: 14.00 },
            { name: 'P2000 | Oceanic', rarity: 'Restricted', price: 9.00 },
            { name: 'SG 553 | Atlas', rarity: 'Restricted', price: 7.00 },
            { name: 'SSG 08 | Ghost Crusader', rarity: 'Mil-Spec', price: 3.60 },
            { name: 'Galil AR | Orange DDPAT', rarity: 'Mil-Spec', price: 2.70 },
            { name: 'UMP-45 | Primal Saber', rarity: 'Mil-Spec', price: 2.10 },
            { name: 'MP9 | Bioleak', rarity: 'Industrial Grade', price: 1.30 },
            { name: 'Dual Berettas | Ventilators', rarity: 'Industrial Grade', price: 0.88 },
            { name: 'MAG-7 | Counter Terrace', rarity: 'Industrial Grade', price: 0.60 },
            { name: 'Negev | Loudmouth', rarity: 'Consumer Grade', price: 0.28 },
            { name: 'Sawed-Off | Fubar', rarity: 'Consumer Grade', price: 0.20 },
            { name: '★ M9 Bayonet', rarity: 'Rare Special', price: 1100.00 }
        ]
    },
    {
        id: 'gamma-case',
        name: 'Gamma Case',
        price: 3.25,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc1IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDBmZjAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDBhYTAwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2c1KSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSIxMDUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxOCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMwMDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiPkdhbW1hPC90ZXh0PjxjaXJjbGUgY3g9IjEwMCIgY3k9IjEzNSIgcj0iMTAiIGZpbGw9IiNmZmQ3MDAiLz48L3N2Zz4=',
        items: [
            { name: 'M4A1-S | Mecha Industries', rarity: 'Covert', price: 125.00 },
            { name: 'Glock-18 | Wasteland Rebel', rarity: 'Covert', price: 98.00 },
            { name: 'P90 | Shallow Grave', rarity: 'Classified', price: 48.00 },
            { name: 'FAMAS | Mecha Industries', rarity: 'Classified', price: 36.00 },
            { name: 'AUG | Aristocrat', rarity: 'Restricted', price: 19.00 },
            { name: 'P2000 | Imperial Dragon', rarity: 'Restricted', price: 13.00 },
            { name: 'M249 | Emerald Poison Dart', rarity: 'Restricted', price: 8.50 },
            { name: 'Five-SeveN | Violent Daimyo', rarity: 'Mil-Spec', price: 4.00 },
            { name: 'MAC-10 | Carnivore', rarity: 'Mil-Spec', price: 3.10 },
            { name: 'Sawed-Off | Limelight', rarity: 'Mil-Spec', price: 2.40 },
            { name: 'SCAR-20 | Powercore', rarity: 'Industrial Grade', price: 1.60 },
            { name: 'SG 553 | Aerial', rarity: 'Industrial Grade', price: 1.00 },
            { name: 'Tec-9 | Ice Cap', rarity: 'Industrial Grade', price: 0.72 },
            { name: 'XM1014 | Slipstream', rarity: 'Consumer Grade', price: 0.35 },
            { name: 'PP-Bizon | Harvester', rarity: 'Consumer Grade', price: 0.24 },
            { name: '★ Bayonet', rarity: 'Rare Special', price: 1050.00 }
        ]
    },
    {
        id: 'gamma-2-case',
        name: 'Gamma 2 Case',
        price: 3.10,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc2IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDBhYTAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDA2NjAwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2c2KSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSI5NSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+R2FtbWEgMjwvdGV4dD48dGV4dCB4PSIxMDAiIHk9IjExNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjEyIiBmaWxsPSIjZmZmIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5DYXNlPC90ZXh0Pjwvc3ZnPg==',
        items: [
            { name: 'AK-47 | Neon Revolution', rarity: 'Covert', price: 185.00 },
            { name: 'FAMAS | Roll Cage', rarity: 'Classified', price: 52.00 },
            { name: 'Tec-9 | Fuel Injector', rarity: 'Classified', price: 44.00 },
            { name: 'P250 | See Ya Later', rarity: 'Restricted', price: 21.00 },
            { name: 'UMP-45 | Scaffold', rarity: 'Restricted', price: 14.50 },
            { name: 'XM1014 | Black Tie', rarity: 'Restricted', price: 9.50 },
            { name: 'MAG-7 | Petroglyph', rarity: 'Mil-Spec', price: 4.20 },
            { name: 'Negev | Dazzle', rarity: 'Mil-Spec', price: 3.30 },
            { name: 'G3SG1 | Hunter', rarity: 'Mil-Spec', price: 2.60 },
            { name: 'Nova | Exo', rarity: 'Industrial Grade', price: 1.70 },
            { name: 'R8 Revolver | Reboot', rarity: 'Industrial Grade', price: 1.10 },
            { name: 'MP9 | Airlock', rarity: 'Industrial Grade', price: 0.78 },
            { name: 'P90 | Elite Build', rarity: 'Consumer Grade', price: 0.38 },
            { name: 'CZ75-Auto | Imprint', rarity: 'Consumer Grade', price: 0.26 },
            { name: '★ Flip Knife', rarity: 'Rare Special', price: 850.00 }
        ]
    },
    {
        id: 'operation-breakout-case',
        name: 'Operation Breakout Weapon Case',
        price: 2.80,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc3IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZmYwMDAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojYWEwMDAwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2c3KSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSI5NSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE0IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+QnJlYWtvdXQ8L3RleHQ+PHRleHQgeD0iMTAwIiB5PSIxMTUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxMiIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2FzZTwvdGV4dD48L3N2Zz4=',
        items: [
            { name: 'M4A1-S | Cyrex', rarity: 'Covert', price: 140.00 },
            { name: 'P90 | Asiimov', rarity: 'Covert', price: 88.00 },
            { name: 'UMP-45 | Corporal', rarity: 'Classified', price: 40.00 },
            { name: 'CZ75-Auto | Poison Dart', rarity: 'Classified', price: 33.00 },
            { name: 'Desert Eagle | Hand Cannon', rarity: 'Restricted', price: 22.00 },
            { name: 'Five-SeveN | Fowl Play', rarity: 'Restricted', price: 15.00 },
            { name: 'Mac-10 | Curse', rarity: 'Restricted', price: 11.00 },
            { name: 'Glock-18 | Water Elemental', rarity: 'Mil-Spec', price: 4.50 },
            { name: 'M4A4 | Desert-Strike', rarity: 'Mil-Spec', price: 3.40 },
            { name: 'SSG 08 | Detour', rarity: 'Mil-Spec', price: 2.80 },
            { name: 'SG 553 | Pulse', rarity: 'Industrial Grade', price: 1.80 },
            { name: 'Galil AR | Kami', rarity: 'Industrial Grade', price: 1.20 },
            { name: 'SCAR-20 | Cardiac', rarity: 'Industrial Grade', price: 0.82 },
            { name: 'Nova | Rising Skull', rarity: 'Consumer Grade', price: 0.40 },
            { name: 'PP-Bizon | Osiris', rarity: 'Consumer Grade', price: 0.28 },
            { name: '★ Butterfly Knife', rarity: 'Rare Special', price: 1300.00 }
        ]
    },
    {
        id: 'shadow-case',
        name: 'Shadow Case',
        price: 2.60,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc4IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMzMzIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDAwIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2c4KSIgeD0iMzAiIHk9IjUwIiB3aWR0aD0iMTQwIiBoZWlnaHQ9IjEwMCIgcng9IjE1Ii8+PHRleHQgeD0iMTAwIiB5PSIxMDUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxOCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiNmZmYiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNoYWRvdzwvdGV4dD48L3N2Zz4=',
        items: [
            { name: 'SSG 08 | Blood in the Water', rarity: 'Covert', price: 195.00 },
            { name: 'M4A1-S | Golden Coil', rarity: 'Covert', price: 115.00 },
            { name: 'G3SG1 | Flux', rarity: 'Classified', price: 58.00 },
            { name: 'FAMAS | Neural Net', rarity: 'Classified', price: 46.00 },
            { name: 'P250 | Wingshot', rarity: 'Restricted', price: 24.00 },
            { name: 'USP-S | Kill Confirmed', rarity: 'Restricted', price: 17.00 },
            { name: 'Galil AR | Stone Cold', rarity: 'Restricted', price: 12.00 },
            { name: 'Desert Eagle | Kumicho Dragon', rarity: 'Mil-Spec', price: 4.80 },
            { name: 'M249 | Shipping Forecast', rarity: 'Mil-Spec', price: 3.60 },
            { name: 'P2000 | Pathfinder', rarity: 'Mil-Spec', price: 3.00 },
            { name: 'MP7 | Special Delivery', rarity: 'Industrial Grade', price: 1.90 },
            { name: 'AUG | Ricochet', rarity: 'Industrial Grade', price: 1.30 },
            { name: 'Sawed-Off | Wasteland Princess', rarity: 'Industrial Grade', price: 0.86 },
            { name: 'Negev | Bratatat', rarity: 'Consumer Grade', price: 0.42 },
            { name: 'Dual Berettas | Duelist', rarity: 'Consumer Grade', price: 0.30 },
            { name: '★ Shadow Daggers', rarity: 'Rare Special', price: 750.00 }
        ]
    },
    {
        id: 'spectrum-case',
        name: 'Spectrum Case',
        price: 2.95,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9Imc5IiB4MT0iMCUiIHkxPSIwJSIgeDI9IjEwMCUiIHkyPSIxMDAlIj48c3RvcCBvZmZzZXQ9IjAlIiBzdHlsZT0ic3RvcC1jb2xvcjojZmYwMGZmIi8+PHN0b3Agb2Zmc2V0PSI1MCUiIHN0eWxlPSJzdG9wLWNvbG9yOiMwMGZmZmYiLz48c3RvcCBvZmZzZXQ9IjEwMCUiIHN0eWxlPSJzdG9wLWNvbG9yOiNmZmZmMDAiLz48L2xpbmVhckdyYWRpZW50PjwvZGVmcz48cmVjdCBmaWxsPSIjMWIyODM4IiB3aWR0aD0iMjAwIiBoZWlnaHQ9IjIwMCIvPjxyZWN0IGZpbGw9InVybCgjZzkpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzAwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+U3BlY3RydW08L3RleHQ+PC9zdmc+',
        items: [
            { name: 'AK-47 | Bloodsport', rarity: 'Covert', price: 165.00 },
            { name: 'USP-S | Neo-Noir', rarity: 'Covert', price: 105.00 },
            { name: 'M4A1-S | Decimator', rarity: 'Classified', price: 62.00 },
            { name: 'CZ75-Auto | Xiangliu', rarity: 'Classified', price: 50.00 },
            { name: 'P250 | Ripple', rarity: 'Restricted', price: 26.00 },
            { name: 'MAC-10 | Candy Apple', rarity: 'Restricted', price: 18.00 },
            { name: 'UMP-45 | Scaffold', rarity: 'Restricted', price: 13.50 },
            { name: 'AUG | Amber Slipstream', rarity: 'Mil-Spec', price: 5.20 },
            { name: 'Tec-9 | Terrace', rarity: 'Mil-Spec', price: 3.90 },
            { name: 'Sawed-Off | Zander', rarity: 'Mil-Spec', price: 3.20 },
            { name: 'Galil AR | Crimson Tsunami', rarity: 'Industrial Grade', price: 2.00 },
            { name: 'MP9 | Goo', rarity: 'Industrial Grade', price: 1.40 },
            { name: 'PP-Bizon | Harvester', rarity: 'Industrial Grade', price: 0.92 },
            { name: 'Five-SeveN | Capillary', rarity: 'Consumer Grade', price: 0.45 },
            { name: 'Nova | Bloomstick', rarity: 'Consumer Grade', price: 0.32 },
            { name: '★ Bowie Knife', rarity: 'Rare Special', price: 900.00 }
        ]
    },
    {
        id: 'spectrum-2-case',
        name: 'Spectrum 2 Case',
        price: 2.85,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxMCIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I2ZmZmYwMCIvPjxzdG9wIG9mZnNldD0iNTAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDBmZjAwIi8+PHN0b3Agb2Zmc2V0PSIxMDAlIiBzdHlsZT0ic3RvcC1jb2xvcjojMDAwMGZmIi8+PC9saW5lYXJHcmFkaWVudD48L2RlZnM+PHJlY3QgZmlsbD0iIzFiMjgzOCIgd2lkdGg9IjIwMCIgaGVpZ2h0PSIyMDAiLz48cmVjdCBmaWxsPSJ1cmwoI2cxMCkiIHg9IjMwIiB5PSI1MCIgd2lkdGg9IjE0MCIgaGVpZ2h0PSIxMDAiIHJ4PSIxNSIvPjx0ZXh0IHg9IjEwMCIgeT0iOTUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxNCIgZm9udC13ZWlnaHQ9ImJvbGQiIGZpbGw9IiMwMDAiIHRleHQtYW5jaG9yPSJtaWRkbGUiPlNwZWN0cnVtIDI8L3RleHQ+PHRleHQgeD0iMTAwIiB5PSIxMTUiIGZvbnQtZmFtaWx5PSJBcmlhbCIgZm9udC1zaXplPSIxMiIgZmlsbD0iIzAwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2FzZTwvdGV4dD48L3N2Zz4=',
        items: [
            { name: 'AK-47 | The Empress', rarity: 'Covert', price: 175.00 },
            { name: 'M4A1-S | Leaded Glass', rarity: 'Classified', price: 68.00 },
            { name: 'MAC-10 | Last Dive', rarity: 'Classified', price: 54.00 },
            { name: 'P250 | See Ya Later', rarity: 'Restricted', price: 28.00 },
            { name: 'PP-Bizon | High Roller', rarity: 'Restricted', price: 19.50 },
            { name: 'Sawed-Off | Wasteland Princess', rarity: 'Restricted', price: 14.80 },
            { name: 'Five-SeveN | Flame Test', rarity: 'Mil-Spec', price: 5.60 },
            { name: 'UMP-45 | Exposure', rarity: 'Mil-Spec', price: 4.10 },
            { name: 'XM1014 | Oxide Blaze', rarity: 'Mil-Spec', price: 3.50 },
            { name: 'SSG 08 | Mainframe', rarity: 'Industrial Grade', price: 2.10 },
            { name: 'MP9 | Goo', rarity: 'Industrial Grade', price: 1.50 },
            { name: 'G3SG1 | Hunter', rarity: 'Industrial Grade', price: 0.98 },
            { name: 'Galil AR | Sugar Rush', rarity: 'Consumer Grade', price: 0.48 },
            { name: 'R8 Revolver | Reboot', rarity: 'Consumer Grade', price: 0.34 },
            { name: '★ Huntsman Knife', rarity: 'Rare Special', price: 1000.00 }
        ]
    },
    {
        id: 'prisma-case',
        name: 'Prisma Case',
        price: 3.40,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxMSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I2ZmMTQ5MyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6IzkzNzBkYiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTEpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE4IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+UHJpc21hPC90ZXh0Pjwvc3ZnPg==',
        items: [
            { name: 'AWP | Atheris', rarity: 'Covert', price: 205.00 },
            { name: 'M4A4 | The Emperor', rarity: 'Covert', price: 135.00 },
            { name: 'R8 Revolver | Skull Crusher', rarity: 'Classified', price: 72.00 },
            { name: 'Five-SeveN | Angry Mob', rarity: 'Classified', price: 60.00 },
            { name: 'Desert Eagle | Light Rail', rarity: 'Restricted', price: 30.00 },
            { name: 'XM1014 | Incinegator', rarity: 'Restricted', price: 21.00 },
            { name: 'Tec-9 | Bamboozle', rarity: 'Restricted', price: 16.00 },
            { name: 'Galil AR | Akoben', rarity: 'Mil-Spec', price: 6.00 },
            { name: 'P250 | Verdigris', rarity: 'Mil-Spec', price: 4.40 },
            { name: 'SG 553 | Phantom', rarity: 'Mil-Spec', price: 3.80 },
            { name: 'UMP-45 | Moonrise', rarity: 'Industrial Grade', price: 2.20 },
            { name: 'MAC-10 | Whitefish', rarity: 'Industrial Grade', price: 1.60 },
            { name: 'MP5-SD | Acid Wash', rarity: 'Industrial Grade', price: 1.05 },
            { name: 'Sawed-Off | Devourer', rarity: 'Consumer Grade', price: 0.52 },
            { name: 'P90 | Off World', rarity: 'Consumer Grade', price: 0.36 },
            { name: '★ Stiletto Knife', rarity: 'Rare Special', price: 1150.00 }
        ]
    },
    {
        id: 'danger-zone-case',
        name: 'Danger Zone Case',
        price: 2.45,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxMiIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I2ZmNDUwMCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6I2ZmYTUwMCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTIpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9Ijk1IiBmb250LWZhbWlseT0iQXJpYWwiIGZvbnQtc2l6ZT0iMTQiIGZvbnQtd2VpZ2h0PSJib2xkIiBmaWxsPSIjMDAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5EYW5nZXIgWm9uZTwvdGV4dD48dGV4dCB4PSIxMDAiIHk9IjExNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjEyIiBmaWxsPSIjMDAwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIj5DYXNlPC90ZXh0Pjwvc3ZnPg==',
        items: [
            { name: 'AK-47 | Asiimov', rarity: 'Covert', price: 220.00 },
            { name: 'AWP | Neo-Noir', rarity: 'Covert', price: 145.00 },
            { name: 'Desert Eagle | Mecha Industries', rarity: 'Classified', price: 76.00 },
            { name: 'USP-S | Flashback', rarity: 'Classified', price: 64.00 },
            { name: 'MP5-SD | Phosphor', rarity: 'Restricted', price: 32.00 },
            { name: 'Tec-9 | Fubar', rarity: 'Restricted', price: 22.50 },
            { name: 'Glock-18 | Moonrise', rarity: 'Restricted', price: 17.50 },
            { name: 'Nova | Wood Fired', rarity: 'Mil-Spec', price: 6.50 },
            { name: 'MAG-7 | SWAG-7', rarity: 'Mil-Spec', price: 4.80 },
            { name: 'Negev | Lionfish', rarity: 'Mil-Spec', price: 4.20 },
            { name: 'MP9 | Modest Threat', rarity: 'Industrial Grade', price: 2.40 },
            { name: 'Sawed-Off | Black Sand', rarity: 'Industrial Grade', price: 1.70 },
            { name: 'R8 Revolver | Grip', rarity: 'Industrial Grade', price: 1.12 },
            { name: 'FAMAS | Crypsis', rarity: 'Consumer Grade', price: 0.55 },
            { name: 'P2000 | Woodsman', rarity: 'Consumer Grade', price: 0.38 },
            { name: '★ Ursus Knife', rarity: 'Rare Special', price: 1050.00 }
        ]
    },
    {
        id: 'clutch-case',
        name: 'Clutch Case',
        price: 2.55,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxMyIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6I2RhYTUyMCIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6I2I4ODYwYiIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTMpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE4IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzAwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+Q2x1dGNoPC90ZXh0Pjwvc3ZnPg==',
        items: [
            { name: 'M4A4 | Neo-Noir', rarity: 'Covert', price: 185.00 },
            { name: 'USP-S | Cortex', rarity: 'Classified', price: 80.00 },
            { name: 'MP7 | Cirrus', rarity: 'Classified', price: 66.00 },
            { name: 'Glock-18 | Moonrise', rarity: 'Restricted', price: 34.00 },
            { name: 'P250 | Nevermore', rarity: 'Restricted', price: 24.00 },
            { name: 'Five-SeveN | Hyper Beast', rarity: 'Restricted', price: 18.50 },
            { name: 'MP9 | Black Sand', rarity: 'Mil-Spec', price: 7.00 },
            { name: 'P2000 | Urban Hazard', rarity: 'Mil-Spec', price: 5.20 },
            { name: 'XM1014 | Ziggy', rarity: 'Mil-Spec', price: 4.60 },
            { name: 'UMP-45 | Arctic Wolf', rarity: 'Industrial Grade', price: 2.60 },
            { name: 'AUG | Triqua', rarity: 'Industrial Grade', price: 1.85 },
            { name: 'R8 Revolver | Nitro', rarity: 'Industrial Grade', price: 1.20 },
            { name: 'Negev | Ultralight', rarity: 'Consumer Grade', price: 0.60 },
            { name: 'Nova | Wild Six', rarity: 'Consumer Grade', price: 0.42 },
            { name: '★ Navaja Knife', rarity: 'Rare Special', price: 850.00 }
        ]
    },
    {
        id: 'horizon-case',
        name: 'Horizon Case',
        price: 2.70,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxNCIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6Izg3Y2VlYiIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6IzQ2ODJiNCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTQpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE4IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iIzAwMCIgdGV4dC1hbmNob3I9Im1pZGRsZSI+SG9yaXpvbjwvdGV4dD48L3N2Zz4=',
        items: [
            { name: 'AK-47 | Neon Rider', rarity: 'Covert', price: 195.00 },
            { name: 'Desert Eagle | Code Red', rarity: 'Covert', price: 125.00 },
            { name: 'AWP | PAW', rarity: 'Classified', price: 84.00 },
            { name: 'M4A1-S | Nightmare', rarity: 'Classified', price: 70.00 },
            { name: 'MAC-10 | Pipe Down', rarity: 'Restricted', price: 36.00 },
            { name: 'Five-SeveN | Crimson Blossom', rarity: 'Restricted', price: 25.50 },
            { name: 'AUG | Stymphalian', rarity: 'Restricted', price: 20.00 },
            { name: 'P250 | Nevermore', rarity: 'Mil-Spec', price: 7.50 },
            { name: 'Tec-9 | Snek-9', rarity: 'Mil-Spec', price: 5.60 },
            { name: 'SG 553 | Aloha', rarity: 'Mil-Spec', price: 4.90 },
            { name: 'Nova | Toy Soldier', rarity: 'Industrial Grade', price: 2.80 },
            { name: 'G3SG1 | Violet Murano', rarity: 'Industrial Grade', price: 2.00 },
            { name: 'XM1014 | Oxide Blaze', rarity: 'Industrial Grade', price: 1.30 },
            { name: 'SSG 08 | Threat Detected', rarity: 'Consumer Grade', price: 0.65 },
            { name: 'PP-Bizon | Facility Sketch', rarity: 'Consumer Grade', price: 0.45 },
            { name: '★ Talon Knife', rarity: 'Rare Special', price: 1250.00 }
        ]
    },
    {
        id: 'glove-case',
        name: 'Glove Case',
        price: 3.50,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxNSIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6IzhiNDUxMyIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6I2EwNTIyZCIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTUpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE4IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+R2xvdmU8L3RleHQ+PC9zdmc+',
        items: [
            { name: 'M4A4 | Emperor', rarity: 'Covert', price: 215.00 },
            { name: 'AWP | Fever Dream', rarity: 'Covert', price: 155.00 },
            { name: 'SSG 08 | Dragonfire', rarity: 'Classified', price: 88.00 },
            { name: 'P90 | Shallow Grave', rarity: 'Classified', price: 74.00 },
            { name: 'USP-S | Cyrex', rarity: 'Restricted', price: 38.00 },
            { name: 'Five-SeveN | Hyper Beast', rarity: 'Restricted', price: 27.00 },
            { name: 'Glock-18 | Wasteland Rebel', rarity: 'Restricted', price: 21.50 },
            { name: 'P2000 | Imperial', rarity: 'Mil-Spec', price: 8.00 },
            { name: 'MP9 | Goo', rarity: 'Mil-Spec', price: 6.00 },
            { name: 'MAC-10 | Lapis Gator', rarity: 'Mil-Spec', price: 5.30 },
            { name: 'Sawed-Off | Fubar', rarity: 'Industrial Grade', price: 3.00 },
            { name: 'Tec-9 | Ice Cap', rarity: 'Industrial Grade', price: 2.15 },
            { name: 'MP7 | Cirrus', rarity: 'Industrial Grade', price: 1.40 },
            { name: 'CZ75-Auto | Imprint', rarity: 'Consumer Grade', price: 0.70 },
            { name: 'Dual Berettas | Royal Consorts', rarity: 'Consumer Grade', price: 0.48 },
            { name: '★ Specialist Gloves', rarity: 'Rare Special', price: 1500.00 }
        ]
    },
    {
        id: 'revolver-case',
        name: 'Revolver Case',
        price: 2.35,
        image: 'data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIj48ZGVmcz48bGluZWFyR3JhZGllbnQgaWQ9ImcxNiIgeDE9IjAlIiB5MT0iMCUiIHgyPSIxMDAlIiB5Mj0iMTAwJSI+PHN0b3Agb2Zmc2V0PSIwJSIgc3R5bGU9InN0b3AtY29sb3I6IzY5Njk2OSIvPjxzdG9wIG9mZnNldD0iMTAwJSIgc3R5bGU9InN0b3AtY29sb3I6I2E5YTlhOSIvPjwvbGluZWFyR3JhZGllbnQ+PC9kZWZzPjxyZWN0IGZpbGw9IiMxYjI4MzgiIHdpZHRoPSIyMDAiIGhlaWdodD0iMjAwIi8+PHJlY3QgZmlsbD0idXJsKCNnMTYpIiB4PSIzMCIgeT0iNTAiIHdpZHRoPSIxNDAiIGhlaWdodD0iMTAwIiByeD0iMTUiLz48dGV4dCB4PSIxMDAiIHk9IjEwNSIgZm9udC1mYW1pbHk9IkFyaWFsIiBmb250LXNpemU9IjE2IiBmb250LXdlaWdodD0iYm9sZCIgZmlsbD0iI2ZmZiIgdGV4dC1hbmNob3I9Im1pZGRsZSI+UmV2b2x2ZXI8L3RleHQ+PC9zdmc+',
        items: [
            { name: 'M4A1-S | Hyper Beast', rarity: 'Covert', price: 175.00 },
            { name: 'R8 Revolver | Fade', rarity: 'Covert', price: 105.00 },
            { name: 'AK-47 | Point Disarray', rarity: 'Classified', price: 78.00 },
            { name: 'P90 | Trigon', rarity: 'Classified', price: 62.00 },
            { name: 'Desert Eagle | Corinthian', rarity: 'Restricted', price: 40.00 },
            { name: 'P250 | Cartel', rarity: 'Restricted', price: 28.00 },
            { name: 'Five-SeveN | Retrobution', rarity: 'Restricted', price: 22.00 },
            { name: 'Sawed-Off | Yorick', rarity: 'Mil-Spec', price: 8.50 },
            { name: 'AUG | Ricochet', rarity: 'Mil-Spec', price: 6.40 },
            { name: 'SG 553 | Tiger Moth', rarity: 'Mil-Spec', price: 5.70 },
            { name: 'P2000 | Imperial', rarity: 'Industrial Grade', price: 3.20 },
            { name: 'Negev | Loudmouth', rarity: 'Industrial Grade', price: 2.30 },
            { name: 'M249 | Impact Drill', rarity: 'Industrial Grade', price: 1.50 },
            { name: 'Tec-9 | Avalanche', rarity: 'Consumer Grade', price: 0.75 },
            { name: 'Dual Berettas | Cartel', rarity: 'Consumer Grade', price: 0.52 },
            { name: '★ Shadow Daggers', rarity: 'Rare Special', price: 800.00 }
        ]
    }
];
